# Generated by Django 3.2.14 on 2022-07-17 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_auto_20220717_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='logindata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameModel(
            old_name='book',
            new_name='bookdata',
        ),
    ]
