# Generated by Django 3.2.14 on 2022-07-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_auto_20220717_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdata',
            name='photo',
            field=models.ImageField(default='SOME STRING', upload_to='books'),
        ),
    ]
