# Generated by Django 3.2.14 on 2022-07-23 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_auto_20220717_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdata',
            name='num',
            field=models.IntegerField(default=1),
        ),
    ]
